Controllers/RegistroController.cs
using inmobiliariaBaigorriaDiaz.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace inmobiliariaBaigorriaDiaz.Controllers
{
    [Authorize("Administrador")]
    public class RegistroController : Controller
    {
        private RepositorioRegistro rg = new RepositorioRegistro();
        // GET: RegistroController
        [HttpGet]
        public ActionResult Index(int limite = 5, int paginado = 1, int cantidad = 0)
        {
            ViewBag.limite = limite;

            ViewBag.rol = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

            // Obtener la cantidad total de filas de Propietario
            if (cantidad == 0)
            {
                cantidad = rg.ObtenerCantidadDeFilas();
            }

            // Calcula el número total de páginas
            ViewBag.totalPages = (int)Math.Ceiling((double)cantidad / limite);

            // Establece la página actual en `ViewBag`
            ViewBag.currentPage = paginado;
            return View(rg.ObtenerRegistros(limite, paginado));
        }

        [HttpGet]
        public IActionResult Paginado(int limite, int paginado)
        {
            // Asegúrate de recibir el valor de `limite` y `paginado`
            ViewBag.limite = limite;
            return Json(rg.ObtenerRegistros(limite, paginado));
        }

        // GET: RegistroController/Details/5
        public ActionResult Details(int id)
        {
            return View(rg.ObtenerRegistroPorID(id));
        }

        // POST: RegistroController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RegistroController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RegistroController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/UsoDeInmuebleController.cs
using inmobiliariaBaigorriaDiaz.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Security.Claims;

namespace inmobiliariaBaigorriaDiaz.Controllers
{
    public class UsoDeInmuebleController : Controller
    {
        private RepositorioUsoDeInmueble rudi = new RepositorioUsoDeInmueble();
        // GET: UsoDeInmuebleController
        [HttpGet]
        public ActionResult Index(int limite = 5, int paginado = 1, int cantidad = 0)
        {
            ViewBag.Id = TempData["Id"];
            ViewBag.entidad = "uso de inmueble";
            ViewBag.limite = limite;
            ViewBag.rol = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

            // Obtener la cantidad total de filas de Propietario
            if (cantidad == 0)
            {
                cantidad = rudi.ObtenerCantidadDeFilas();
            }

            // Calcula el número total de páginas
            ViewBag.totalPages = (int)Math.Ceiling((double)cantidad / limite);

            // Establece la página actual en `ViewBag`
            ViewBag.currentPage = paginado;
            return View(rudi.ObtenerUsosDeInmuebles(limite, paginado));
        }

        [HttpGet]
        public IActionResult Paginado(int limite, int paginado)
        {
            // Asegúrate de recibir el valor de `limite` y `paginado`
            ViewBag.limite = limite;
            return Json(rudi.ObtenerUsosDeInmuebles(limite, paginado));
        }

        // GET: UsoDeInmuebleController/Details/5
        public ActionResult Details(int id)
        {
            return View(rudi.ObtenerUsoDeInmueblePorID(id));
        }

        // GET: UsoDeInmuebleController/Create
        public ActionResult Create()
        {
            var usosDeInmuebles = rudi.ObtenerUsosDeInmuebles();
            ViewBag.usosDeInmuebles = usosDeInmuebles;
            return View();
        }

        // POST: UsoDeInmuebleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UsoDeInmueble usoDeInmueble)
        {
            try
            {
                rudi.AltaFisica(usoDeInmueble);
                TempData["Id"] = usoDeInmueble.IdUsoDeInmueble;
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Alta(int id)
        {
            return View(rudi.ObtenerUsoDeInmueblePorID(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Alta(int id, IFormCollection collection)
        {
            try
            {
                rudi.AltaLogica(id);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                ModelState.AddModelError(string.Empty, "Ha ocurrido un error al cargar la página.");
                return View(); // Retorna la vista con el modelo para que el usuario pueda corregir la entrada.
            }
        }

        // GET: UsoDeInmuebleController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(rudi.ObtenerUsoDeInmueblePorID(id));
        }

        // POST: UsoDeInmuebleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, UsoDeInmueble usoDeInmueble)
        {
            try
            {
                UsoDeInmueble? udi = rudi.ObtenerUsoDeInmueblePorID(id);
                if(udi != null){
                    udi.Nombre = usoDeInmueble.Nombre;
                    udi.Estado = usoDeInmueble.Estado;
                    rudi.Modificacion(udi);
                    return RedirectToAction(nameof(Index));
                } else {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message.ToString());
                return RedirectToAction("Edit");
            }
        }

        // GET: UsoDeInmuebleController/Delete/5
        [HttpGet]
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int id)
        {
            return View(rudi.ObtenerUsoDeInmueblePorID(id));
        }

        // POST: UsoDeInmuebleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                rudi.BajaLogica(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public IActionResult NoAutorizado()
        {
            return View(); // Puedes redirigir a una vista específica para mostrar un mensaje de error o realizar alguna acción.
        }

        // Filtro de acción para redirigir si el usuario no está autenticado
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (!User.Identity.IsAuthenticated)
            {
                context.Result = new RedirectResult("/Home/Login");
            }
            base.OnActionExecuting(context);
        }
    }
}

Controllers/UsuarioController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using inmobiliariaBaigorriaDiaz.Models;
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Web.WebPages;

namespace inmobiliariaBaigorriaDiaz.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IWebHostEnvironment environment;
        private RepositorioUsuario ru = new RepositorioUsuario();

        public UsuarioController(IWebHostEnvironment environment)
        {
            this.environment = environment;
        }


        // GET: Usuario
        [HttpGet]
        [Authorize(Roles = "Administrador")]
        public ActionResult Index(int limite = 5, int paginado = 1, int cantidad = 0)
        {
            ViewBag.Id = TempData["Id"];
            ViewBag.entidad = "usuario";
            ViewBag.limite = limite;

            ViewBag.rol = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

            // Obtener la cantidad total de filas de Propietario
            if(cantidad == 0){
                cantidad = ru.ObtenerCantidadDeFilas();
            }

            // Calcula el número total de páginas
            ViewBag.totalPages = (int)Math.Ceiling((double)cantidad / limite);

            // Establece la página actual en `ViewBag`
            ViewBag.currentPage = paginado;
            return View(ru.ObtenerUsuarios(limite, paginado));
        }

        [HttpGet]
        public IActionResult Paginado(int limite, int paginado)
        {
            // Asegúrate de recibir el valor de `limite` y `paginado`
            ViewBag.limite = limite;
            return Json(ru.ObtenerUsuarios(limite, paginado));
        }

        // GET: Usuario/Details/5
        [HttpGet]
        [Authorize(Roles = "Administrador")]
        public ActionResult Details(int id)
        {
            return View(ru.ObtenerUsuarioPorID(id));
        }

        // GET: Usuario/Create
        [HttpGet]
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            ViewBag.Roles = Usuario.ObtenerRoles();
            return View();
        }

        [HttpGet]
        public ActionResult Alta(int id)
        {
            return View(ru.ObtenerUsuarioPorID(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Alta(int id, IFormCollection collection)
        {
            try
            {
                ru.AltaLogica(id);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                ModelState.AddModelError(string.Empty, "Ha ocurrido un error al cargar la página.");
                return View(); // Retorna la vista con el modelo para que el usuario pueda corregir la entrada.
            }
        }

        // GET: Usuario/EditAdministrador/5
        [HttpGet]
        [Authorize(Roles = "Administrador")]
        public ActionResult EditAdministrador(int id)
        {
            ViewBag.Roles = Usuario.ObtenerRoles();
            return View(ru.ObtenerUsuarioPorID(id));
        }

        [HttpPost]
        public async Task<ActionResult> EditAdministrador(int id, Usuario usuario, IFormFile? avatarFile)
        {
            ClaimsIdentity? identity = null;
            if (mismoUsuario(id))
            {
                Console.WriteLine("Tengo la misma identity que el usuario logueado");
                identity = (ClaimsIdentity?)User.Identity;
            }
            try
            {
                if (usuario.Nombre.IsEmpty() || usuario.Apellido.IsEmpty() || usuario.Email.IsEmpty())
                {
                    ModelState.AddModelError("", "No puede haber ningún campo vacío");
                    ViewBag.Roles = Usuario.ObtenerRoles();
                    return View(usuario);
                }
                if (!ModelState.IsValid)
                {
                    // Itera sobre cada par clave-valor en ModelState
                    foreach (var entry in ModelState)
                    {
                        // Obtiene el nombre de la propiedad
                        var propertyName = entry.Key;

                        // Obtiene la colección de errores para la propiedad actual
                        var errors = entry.Value.Errors;

                        // Itera sobre los errores en la colección
                        foreach (var error in errors)
                        {
                            // Accede a la descripción del error
                            var errorMessage = error.ErrorMessage;

                            // Haz lo que necesites con el mensaje de error
                            Console.WriteLine($"Error en la propiedad '{propertyName}': {errorMessage}");
                        }
                    }
                    return View();
                }
                else
                {
                    Usuario? u = ru.ObtenerUsuarioPorID(id);
                    if (u != null)
                    {
                        u.Nombre = usuario.Nombre;
                        u.Apellido = usuario.Apellido;
                        u.Email = usuario.Email;
                        u.Rol = usuario.Rol;
                        if (usuario.Clave != null)
                        {
                            u.Clave = Usuario.hashearClave(usuario.Clave);
                        }
                        if(!u.AvatarURL.IsEmpty()){
                            var ruta = Path.Combine(environment.WebRootPath, "uploads", $"avatar_{id}" + Path.GetExtension(u.AvatarURL));
                            if (System.IO.File.Exists(ruta))
                            {
                                Console.WriteLine("¡Archivo eliminado!");
                                System.IO.File.Delete(ruta);
                            }
                        }
                        // Actualizar la URL del avatar en la base de datos
                        if (avatarFile != null)
                        {
                            Console.WriteLine("avatarFile no es nulo");
                            var resizedImagePath = await ProcesarAvatarAsync(u, avatarFile);
                            if (resizedImagePath == null)
                            {
                                Console.WriteLine("reizedImagePath es null");
                                return View(usuario); // Retorna la vista con errores de validación si la extensión del archivo no es válida
                            }

                            u.AvatarURL = resizedImagePath;

                            // Actualizar la claim de AvatarURL del usuario
                            if (identity != null)
                            {
                                var existingClaim = identity.FindFirst(ClaimTypes.UserData);

                                // Eliminar la claim existente de AvatarURL
                                if (existingClaim != null)
                                {
                                    identity.RemoveClaim(existingClaim);
                                }

                                // Agregar la nueva claim de AvatarURL
                                identity.AddClaim(new Claim(ClaimTypes.UserData, resizedImagePath));

                                // Actualizar los claims del usuario en la autenticación del usuario
                                await HttpContext.SignInAsync(new ClaimsPrincipal(identity));
                            }
                        }
                        else
                        {
                            // Si no se proporciona un archivo, simplemente redirige a la página de índice
                            u.AvatarURL = "";

                            // Actualizar la claim de AvatarURL del usuario
                            if (identity != null)
                            {
                                var existingClaim = identity.FindFirst(ClaimTypes.UserData);

                                // Eliminar la claim existente de AvatarURL
                                if (existingClaim != null)
                                {
                                    identity.RemoveClaim(existingClaim);
                                }

                                // Agregar la nueva claim de AvatarURL
                                identity.AddClaim(new Claim(ClaimTypes.UserData, ""));

                                // Actualizar los claims del usuario en la autenticación del usuario
                                await HttpContext.SignInAsync(new ClaimsPrincipal(identity));
                            }
                        }
                        if (identity != null)
                        {
                            var nameClaim = identity.FindFirst(ClaimTypes.Name);
                            var emailClaim = identity.FindFirst(ClaimTypes.Email);
                            var rolClaim = identity.FindFirst(ClaimTypes.Role);

                            if (nameClaim != null)
                            {
                                identity.RemoveClaim(nameClaim);
                            }
                            if (emailClaim != null)
                            {
                                identity.RemoveClaim(emailClaim);
                            }
                            if (rolClaim != null)
                            {
                                identity.RemoveClaim(rolClaim);
                            }

                            identity.AddClaim(new Claim(ClaimTypes.Name, u.ToString()));
                            identity.AddClaim(new Claim(ClaimTypes.Email, u.Email));
                            identity.AddClaim(new Claim(ClaimTypes.Role, u.RolNombre));

Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inmobiliaria Baigorria-Diaz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />
    <link rel="stylesheet" href="~/inmobiliariaBaigorriaDiaz.styles.css" asp-append-version="true" />
</head>

<body>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <header>
        <nav
            class="container-fluid navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="navbar-collapse container-fluid collapse d-sm-inline-flex navbar-custom">
                @if (!User.Identity.IsAuthenticated)
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fa fa-home" aria-hidden="true"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Login">
                                <i class="fa fa-key" aria-hidden="true"></i> Acceder</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fa fa-home" aria-hidden="true"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Propietario" asp-action="Index">
                                <i class="fa-solid fa-user-tie"></i> Propietarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Inquilino" asp-action="Index">
                                <i class="fa fa-users" aria-hidden="true"></i> Inquilinos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Inmueble" asp-action="Index">
                                <i class="fas fa-hotel"></i> Inmuebles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="TipoDeInmueble" asp-action="Index">
                                <i class="fas fa-warehouse"></i> Tipo de inmuebles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="UsoDeInmueble" asp-action="Index">
                                <i class="fas fa-store"></i> Uso de inmuebles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Contrato" asp-action="Index">
                                <i class="fas fa-file-contract"></i> Contratos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Pago" asp-action="Index">
                                <i class="fas fa-money-bill-wave"></i> Pagos</a>
                        </li>
                        @if (User.IsInRole("Administrador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Usuario" asp-action="Index">
                                    <i class="fa-solid fa-users-gear"></i> Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Registro" asp-action="Index">
                                    <i class="fa fa-table"></i> Registro</a>
                            </li>
                        }
                        <li class="nav-item dropdown">
                            <div class="dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink"
                                    role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        var avatarUrl = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.UserData)?.Value;
                                        if (!string.IsNullOrEmpty(avatarUrl))
                                        {
                                            <img src="@avatarUrl" alt="Avatar del usuario" class="rounded-circle"
                                                style="width: 30px; height: 30px;" />
                                        }
                                        else
                                        {
                                            <img src="~/guest.jpg" alt="Avatar predeterminado" class="rounded-circle"
                                                style="width: 30px; height: 30px;" />
                                        }
                                        <span class="ml-2">Bienvenido @User.Identity.Name</span>
                                    }
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end"
                                    aria-labelledby="navbarDropdownMenuLink">
                                    @{
                                        // Obtener el valor de la Claim PrimarySid
                                        var userIdClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.PrimarySid);
                                        var userId = userIdClaim?.Value;
                                    }
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Usuario"
                                            asp-action="EditPerfil" asp-route-id="@userId">Editar perfil</a>
                                    </li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Usuario"
                                            asp-action="EditAvatar" asp-route-id="@userId">Cambiar Avatar</a>
                                    </li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Usuario"
                                            asp-action="EditClaveEmpleado" asp-route-id="@userId">Cambiar
                                            contraseña</a></li>
                                    <div class="dropdown-divider"></div>
                                    <li><a class="dropdown-item" href="@Url.Action("Logout", "Home")">Desloguearme</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                }
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            <div class="">
                @if (ViewBag.Id != null)
                {
                    <div id="alertMessage" class="alert alert-primary alert-dismissible fade show fadeOut" role="alert">
                        <strong>¡Éxito!</strong> datos guardados correctamente!
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&#x2714;</span>
                        </button>
                    </div>
                    <script>
                        setTimeout(function () {
                            var alertMessage = document.getElementById('alertMessage');
                            alertMessage.style.display = 'none';
                            alertMessage.remove();
                        }, 4000);
                    </script>

                }
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - inmobiliariaBaigorriaDiaz - <a asp-area="" asp-controller="Home"
                asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>