Models/propietario.cs
using System.ComponentModel.DataAnnotations;

namespace inmobiliariaBaigorriaDiaz.Models
{
    public class Propietario
    {
        [Display(Name = "ID del propietario")]
        public int IdPropietario { get; set; }
        [Required]
        public string Nombre { get; set; } = "";
        [Required]
        public string Apellido { get; set; } = "";
        [Display(Name = "Teléfono")]
        public string? Telefono { get; set; }
        [EmailAddress]
        public string? Email { get; set; }
        [Required]
        public string DNI { get; set; } = "";
        [Required]
        public bool Estado { get; set; }
        public override string ToString()
        {
            return $"{Apellido} {Nombre}";
        }
    }
}

Controllers/PropietarioController.cs
using inmobiliariaBaigorriaDiaz.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Security.Claims;

namespace inmobiliariaBaigorriaDiaz.Controllers
{
    public class PropietarioController : Controller
    {
        private RepositorioPropietario rp = new RepositorioPropietario();

        // GET: Propietario
        [HttpGet]
        public ActionResult Index(int limite = 5, int paginado = 1, int cantidad = 0)
        {
            ViewBag.Id = TempData["Id"];
            ViewBag.entidad = "propietario";
            // Establece `limite` en `ViewBag` para usarlo en la vista
            ViewBag.limite = limite;

            ViewBag.rol = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

            // Obtener la cantidad total de filas de Propietario
            if(cantidad == 0){
                cantidad = rp.ObtenerCantidadDeFilas();
            }

            // Calcula el número total de páginas
            ViewBag.totalPages = (int)Math.Ceiling((double)cantidad / limite);

            // Establece la página actual en `ViewBag`
            ViewBag.currentPage = paginado;
            // Devuelve la vista con los datos de `propietarios`
            return View(rp.ObtenerPropietarios(limite, paginado));
        }

        [HttpGet]
        public IActionResult Paginado(int limite, int paginado)
        {
            // Asegúrate de recibir el valor de `limite` y `paginado`
            ViewBag.limite = limite;
            return Json(rp.ObtenerPropietarios(limite, paginado));
        }

        // GET: Propietario/Details/5
        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(rp.ObtenerPropietarioPorID(id));
        }

        // GET: Propietrio/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Propietario/Create
        [HttpPost]
        public ActionResult Create(Propietario propietario)
        {
            try
            {
                rp.AltaFisica(propietario);
                TempData["Id"] = propietario.IdPropietario;
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Alta(int id)
        {
            return View(rp.ObtenerPropietarioPorID(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Alta(int id, IFormCollection collection)
        {
            try
            {
                rp.AltaLogica(id);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                ModelState.AddModelError(string.Empty, "Ha ocurrido un error al cargar la página.");
                return View(); // Retorna la vista con el modelo para que el usuario pueda corregir la entrada.
            }
        }

        // GET: Propietario/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(rp.ObtenerPropietarioPorID(id));
        }

        // POST: Propietario/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Propietario propietario)
        {
            try
            {
                // TODO: Add update logic here
                Propietario p = rp.ObtenerPropietarioPorID(id);
                if (p != null)
                {
                    p.DNI = propietario.DNI;
                    p.Nombre = propietario.Nombre;
                    p.Apellido = propietario.Apellido;
                    p.Email = propietario.Email;
                    p.Telefono = propietario.Telefono;
                    p.Estado = propietario.Estado;
                    rp.Modificacion(p);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message.ToString());
                return RedirectToAction("Edit");
            }
        }

        [HttpGet]
        public ActionResult BuscarPropietario(int dni)
        {
            var propietario = rp.ObtenerPropietarioPorDNI(dni);
            if (propietario != null)
            {
                // Si el inquilino se encuentra, devolvemos los datos como un objeto JSON con la propiedad "success" igual a true
                // y los datos del inquilino en la propiedad "inquilino"

                return Json(new { success = true, propietario = propietario });
            }
            else
            {
                // Si el inquilino no se encuentra, devolvemos un objeto JSON con la propiedad "success" igual a false
                return Json(new { success = false });
            }
        }

        [HttpPost]
        public ActionResult CreateJSON([FromBody] Propietario propietario)
        {
            try
            {
                // Realizar las operaciones necesarias con el objeto propietario
                rp.AltaFisica(propietario);
                TempData["Id"] = propietario.IdPropietario;
                return Json(new { success = true, propietario.IdPropietario, message = "propietario creado exitosamente" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        // GET: Propietario/Delete/5
        [HttpGet]
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int id)
        {
            if (!User.IsInRole("Administrador"))
            {
                TempData["ErrorMessage"] = "No tienes permiso para realizar esta acción.";
                return RedirectToAction(nameof(Index));
            }
            return View(rp.ObtenerPropietarioPorID(id));
        }

        // POST: Propietario/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                rp.BajaLogica(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public IActionResult NoAutorizado()
        {
            return View();
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (!User.Identity.IsAuthenticated)
            {
                context.Result = new RedirectResult("/Home/Login");
            }
            base.OnActionExecuting(context);
        }
    }
}

Views/Propietario/Alta.cshtml
@model inmobiliariaBaigorriaDiaz.Models.Propietario

@{
	ViewData["Title"] = "Alta";
}

<div class="container mt-3">
	<div class="row justify-content-center">
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<h1 class="text-center"><b>ALTA DEL PROPIETARIO</b></h1>
					<h2 class="text-center">¿Está seguro que desea dar de alta de nuevo al siguiente propietario?</h2>
					<hr />
					<dl class="row">
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.DNI)
						</dt>
						<dd class="col-sm-8">
							@Html.DisplayFor(model => model.DNI)
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Apellido)
						</dt>
						<dd class="col-sm-8">
							@Html.DisplayFor(model => model.Apellido)
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Nombre)
						</dt>
						<dd class="col-sm-8">
							@Html.DisplayFor(model => model.Nombre)
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Telefono)
						</dt>
						<dd class="col-sm-8">
							@if (Model.Telefono != null)
							{
								@Html.DisplayFor(model => model.Telefono)
							}
							else
							{
								<text>No declarado</text>
							}
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Email)
						</dt>
						<dd class="col-sm-8">
							@if (Model.Email != null)
							{
								@Html.DisplayFor(model => model.Email)
							}
							else
							{
								<text>No declarado</text>
							}
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Estado)
						</dt>
						<dd class="col-sm-8">
							@if (Model.Estado)
							{
								@Html.Label("Alta")
							}
							else
							{
								@Html.Label("Baja")
							}
						</dd>
						<dd class="col-sm-12"></dd>
					</dl>
					<div class="text-center">
						<form asp-action="Alta">
							<input type="submit" value="Alta" class="btn btn-success" style="margin-right: 30px;" />
							<button type="button" onclick="window.location.href='@Url.Action("Index", "Propietario")'"
								class="btn btn-outline-warning" style="font-weight: bold; border-width: 2px;"> Volver a
								la
								Lista</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Views/Propietario/Create.cshtml
@model inmobiliariaBaigorriaDiaz.Models.Propietario

@{
    ViewData["Title"] = "Create";
}

<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center"><b>ALTA DE PROPIETARIO</b></h1>
                    <form asp-action="Create" class="needs-validation" novalidate>
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="DNI" class="control-label">DNI</label>
                            <div class="input-group">
                                <input asp-for="DNI" class="form-control" required />
                                <span class="input-group-text">
                                    <i class="fa fa-check text-success d-none"></i>
                                    <i class="fa fa-times text-danger d-none"></i>
                                </span>
                                <div class="invalid-feedback">Por favor ingrese un DNI válido.</div>
                            </div>
                            <span asp-validation-for="DNI" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Apellido" class="control-label">Apellido</label>
                            <div class="input-group">
                                <input asp-for="Apellido" class="form-control" required />
                                <span class="input-group-text">
                                    <i class="fa fa-check text-success d-none"></i>
                                    <i class="fa fa-times text-danger d-none"></i>
                                </span>
                                <div class="invalid-feedback">Por favor ingrese un Apellido válido.</div>
                            </div>
                            <span asp-validation-for="Apellido" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Nombre" class="control-label">Nombre</label>
                            <div class="input-group">
                                <input asp-for="Nombre" class="form-control" required />
                                <span class="input-group-text">
                                    <i class="fa fa-check text-success d-none"></i>
                                    <i class="fa fa-times text-danger d-none"></i>
                                </span>
                                <div class="invalid-feedback">Por favor ingrese un Nombre válido.</div>
                            </div>
                            <span asp-validation-for="Nombre" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Telefono" class="control-label">Teléfono</label>
                            <input asp-for="Telefono" class="form-control" />
                            <span asp-validation-for="Telefono" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label">Email</label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group text-center mt-2">
                            <button type="submit" class="btn btn-primary">Alta</button>
                            <a href="@Url.Action("Index", "Propietario")" class="m-2 p-2 btn btn-outline-warning">Volver a la
                                Lista</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        // Validar los campos y mostrar los iconos de verificación
        $(document).ready(function () {
            $('.input-group input').on('input', function () {
                var inputGroup = $(this).closest('.input-group');
                var iconCheck = inputGroup.find('.fa-check');
                var iconTimes = inputGroup.find('.fa-times');
                if ($(this).val().trim() !== '') {
                    iconCheck.removeClass('d-none');
                    iconTimes.addClass('d-none');
                } else {
                    iconCheck.addClass('d-none');
                    iconTimes.removeClass('d-none');
                }
            });
        });
    </script>
}

Views/Propietario/Delete.cshtml
@model inmobiliariaBaigorriaDiaz.Models.Propietario

@{
    ViewData["Title"] = "Delete";
}

<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center"><b>BAJA DEL PROPIETARIO</b></h1>
                    <h2 class="text-center">¿Está seguro que desea dar de baja al siguiente propietario?</h2>
                    <hr />
                    <dl class="row">
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.DNI)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.DNI)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Apellido)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Apellido)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Nombre)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Nombre)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Telefono)
                        </dt>
                        <dd class="col-sm-8">
                            @if (Model.Telefono != null)
                            {
                                @Html.DisplayFor(model => model.Telefono)
                            }
                            else
                            {
                                <text>No declarado</text>
                            }
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Email)
                        </dt>
                        <dd class="col-sm-8">
                            @if (Model.Email != null)
                            {
                                @Html.DisplayFor(model => model.Email)
                            }
                            else
                            {
                                <text>No declarado</text>
                            }
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Estado)
                        </dt>
                        <dd class="col-sm-8">
                            @if (Model.Estado)
                            {
                                @Html.Label("Alta")
                            }
                            else
                            {
                                @Html.Label("Baja")
                            }
                        </dd>
                        <dd class="col-sm-12"></dd>
                    </dl>
                    <div class="text-center">
                        <form asp-action="Delete">
                            <input type="submit" value="Baja" class="btn btn-danger" style="margin-right: 30px;" />
                            <button type="button" onclick="window.location.href='@Url.Action("Index", "Propietario")'"
                                class="btn btn-outline-warning" style="font-weight: bold; border-width: 2px;"> Volver a la
                                Lista</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Propietario/Details.cshtml
@model inmobiliariaBaigorriaDiaz.Models.Propietario

@{
    ViewData["Title"] = "Details";
}

<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center"><b>DETALLE DEL PROPIETARIO</b></h1>
                    <hr />
                    <dl class="row">
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.DNI)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.DNI)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Apellido)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Apellido)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Nombre)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Nombre)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Telefono)
                        </dt>
                        <dd class="col-sm-8">
                            @if (Model.Telefono != null)
                            {
                                @Html.DisplayFor(model => model.Telefono)
                            }
                            else
                            {
                                <text>No declarado</text>
                            }
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Email)
                        </dt>
                        <dd class="col-sm-8">
                            @if (Model.Email != null)
                            {
                                @Html.DisplayFor(model => model.Email)
                            }
                            else
                            {
                                <text>No declarado</text>
                            }
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Estado)
                        </dt>
                        <dd class="col-sm-8">
                            @if (Model.Estado)
                            {
                                @Html.Label("Alta")
                            }
                            else
                            {
                                @Html.Label("Baja")
                            }
                        </dd>
                        <dt class="col-sm-12"></dt>
                    </dl>
                    <div class="text-center mt-3">
                        <a href="@Url.Action("Edit", new { id = Model.IdPropietario })"
                            class="btn btn-primary btn-editar" style="margin-right: 30px;">Editar</a>
                        <button type="button" onclick="window.location.href='@Url.Action("Index", "Propietario")'"
                            class="btn btn-outline-warning" style="font-weight: bold; border-width: 2px;"> Volver a la
                            Lista</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Propietario/Edit.cshtml
@model inmobiliariaBaigorriaDiaz.Models.Propietario

@{
    ViewData["Title"] = "Edit";
}

<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center"><b>ACTUALIZACIÓN DEL PROPIETARIO</b></h1>
                    <hr />
                    <dl class="row">
                        <form asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="IdPropietario" class="control-label"></label>
                                <input asp-for="IdPropietario" class="form-control" readonly />
                            </div>
                            <div class="form-group">
                                <label asp-for="DNI" class="control-label"></label>
                                <input asp-for="DNI" class="form-control" />
                                <span asp-validation-for="DNI" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Apellido" class="control-label"></label>
                                <input asp-for="Apellido" class="form-control" />
                                <span asp-validation-for="Apellido" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Nombre" class="control-label"></label>
                                <input asp-for="Nombre" class="form-control" />
                                <span asp-validation-for="Nombre" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Telefono" class="control-label"></label>
                                <input asp-for="Telefono" class="form-control" />
                                <span asp-validation-for="Telefono" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Email" class="control-label"></label>
                                <input asp-for="Email" class="form-control" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                            <br>
                            <div class="form-group text-center">
                                <input type="submit" value="Guardar" class="btn btn-primary btn-guardar"
                                    style="margin-right: 30px;" />
                                <button type="button"
                                    onclick="window.location.href='@Url.Action("Index", "Propietario")'"
                                    class="btn btn-outline-warning" style="font-weight: bold; border-width: 2px;">
                                    Volver a la
                                    Lista</button>
                            </div>
                        </form>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>