Models/inmueble.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace inmobiliariaBaigorriaDiaz.Models;

public class Inmueble
{
    [Key]
    [Display(Name = "Nº de Inmueble")]
    public int IdInmueble { get; set; }

    [Required]
    [Display(Name = "Tipo")]
    public int IdTipoDeInmueble { get; set; }

    [ForeignKey(nameof(IdTipoDeInmueble))]
    public TipoDeInmueble Tipo { get; set; } = new TipoDeInmueble();

    [Required]
    [Display(Name = "Uso")]
    public int IdUsoDeInmueble { get; set; }

    [ForeignKey(nameof(IdUsoDeInmueble))]
    public UsoDeInmueble Uso { get; set; } = new UsoDeInmueble();

    [Required]
    [Display(Name = "Dirección")]
    public string Direccion { get; set; } = "";

    [Required]
    public int Ambientes { get; set; }

    [Required]
    public decimal Superficie { get; set; }

    public decimal? Longitud { get; set; }

    public decimal? Latitud { get; set; }

    [Required]
    public decimal Precio { get; set; }

    [Required]
    [Display(Name = "Estado del inmueble")]
    public bool Estado { get; set; }

    [Display(Name = "Dueño")]
    public int IdPropietario { get; set; }

    [ForeignKey(nameof(IdPropietario))]
    [Display(Name = "Propietario")]
    public Propietario Duenio { get; set; } = new Propietario();

}

Controllers/InmuebleController.cs
using inmobiliariaBaigorriaDiaz.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Security.Claims;

namespace inmobiliariaBaigorriaDiaz.Controllers
{
    public class InmuebleController : Controller
    {
        private RepositorioPropietario repoP = new RepositorioPropietario();
        private RepositorioInmueble repoI = new RepositorioInmueble();
        private RepositorioTipoDeInmueble repoTI = new RepositorioTipoDeInmueble();
        private RepositorioUsoDeInmueble repoUI = new RepositorioUsoDeInmueble();
        private RepositorioInquilino repoIn = new RepositorioInquilino();

        // GET: Inmueble
        public ActionResult Index(int limite = 5, int paginado = 1, int cantidad = 0)
        {
            ViewBag.Id = TempData["Id"];
            ViewBag.entidad = "inmueble";
            ViewBag.limite = limite;

            ViewBag.rol = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

            // Obtener la cantidad total de filas de Propietario
            if (cantidad == 0)
            {
                cantidad = repoI.ObtenerCantidadDeFilas();
            }

            // Calcula el número total de páginas
            ViewBag.totalPages = (int)Math.Ceiling((double)cantidad / limite);

            // Establece la página actual en `ViewBag`
            ViewBag.currentPage = paginado;
            return View(repoI.ObtenerInmuebles(limite, paginado));
        }

        [HttpGet]
        public IActionResult Paginado(int limite, int paginado)
        {
            // Asegúrate de recibir el valor de `limite` y `paginado`
            ViewBag.limite = limite;
            return Json(repoI.ObtenerInmuebles(limite, paginado));
        }

        // GET: Inmueble/Details/5
        public ActionResult Details(int id)
        {
            ;
            return View(repoI.ObtenerInmueblePorID(id));
        }

        // GET: Inmueble/Create
        [HttpGet]
        public ActionResult Create(int id)
        {
            try
            {
                ViewBag.Duenio = repoP.ObtenerPropietarioPorID(id);
                Console.WriteLine(ViewBag.Duenio);
                ViewBag.TiposDeInmuebles = repoTI.ObtenerTiposDeInmuebles();
                ViewBag.UsosDeInmuebles = repoUI.ObtenerUsosDeInmuebles();
                return View();
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                ModelState.AddModelError(string.Empty, "Ha ocurrido un error al cargar la página.");
                return View();
            }
        }


        // POST: Inmueble/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Inmueble inmueble)
        {
            try
            {
                repoI.AltaFisica(inmueble);
                TempData["Id"] = inmueble.IdInmueble;
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                ModelState.AddModelError(string.Empty, "Ha ocurrido un error al cargar la página.");
                return View(); // Retorna la vista con el modelo para que el usuario pueda corregir la entrada.
            }
        }

        [HttpGet]
        public ActionResult Alta(int id)
        {
            return View(repoI.ObtenerInmueblePorID(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Alta(int id, IFormCollection collection)
        {
            try
            {
                repoI.AltaLogica(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                ModelState.AddModelError(string.Empty, "Ha ocurrido un error al cargar la página.");
                return View(); // Retorna la vista con el modelo para que el usuario pueda corregir la entrada.
            }
        }

        // GET: Inmueble/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Propietarios = repoP.ObtenerPropietarios();
            ViewBag.TiposDeInmuebles = repoTI.ObtenerTiposDeInmuebles();
            ViewBag.UsosDeInmuebles = repoUI.ObtenerUsosDeInmuebles();
            return View(repoI.ObtenerInmueblePorID(id));
        }

        // POST: Inmueble/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Inmueble inmueble)
        {
            try
            {
                Inmueble? inmuebleBD = repoI.ObtenerInmueblePorID(id);
                if (inmuebleBD != null)
                {
                    inmuebleBD.IdTipoDeInmueble = inmueble.IdTipoDeInmueble;
                    inmuebleBD.IdUsoDeInmueble = inmueble.IdUsoDeInmueble;
                    inmuebleBD.IdPropietario = inmueble.IdPropietario;
                    inmuebleBD.Direccion = inmueble.Direccion;
                    inmuebleBD.Ambientes = inmueble.Ambientes;
                    inmuebleBD.Superficie = inmueble.Superficie;
                    inmuebleBD.Longitud = inmueble.Longitud;
                    inmuebleBD.Latitud = inmueble.Latitud;
                    inmuebleBD.Precio = inmueble.Precio;
                    repoI.ModificarInmueble(inmuebleBD);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                // Maneja la excepción o imprime detalles para depuración
                Console.WriteLine(ex.ToString());
                return View();
            }
        }

        // GET: Inmueble/Delete/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int id)
        {
            return View(repoI.ObtenerInmueblePorID(id));
        }

        // POST: Inmueble/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                repoI.BajaLogica(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Buscar(int id)
        {
            ViewBag.IdInquilino = id;
            ViewBag.TiposDeInmuebles = repoTI.ObtenerTiposDeInmuebles();
            ViewBag.UsosDeInmuebles = repoUI.ObtenerUsosDeInmuebles();
            var inquilino = repoIn.ObtenerInquilinoPorID(id);
            ViewBag.Inquilino = inquilino;
            return View();
        }

        // POST: /Buscar
        [HttpPost]
        public IActionResult Buscar(int? IdUsoDeInmueble, int? IdTipoDeInmueble, int? ambientes, decimal? precioDesde, decimal? precioHasta, DateTime? fechaDesde, DateTime? fechaHasta)
        {
            Console.WriteLine("Uso de inmueble: " + IdUsoDeInmueble);
            var inmueblesEncontrados = repoI.BuscarInmuebles(IdUsoDeInmueble, IdTipoDeInmueble, ambientes, precioDesde, precioHasta, fechaDesde, fechaHasta);
            return Json(inmueblesEncontrados);
        }


        [HttpGet]
        public IActionResult ObtenerInmueblesPorUso(int id)
        {
            var inmuebles = repoI.ObtenerInmueblesPorUso(id);
            return Json(inmuebles);
        }

        [HttpGet]
        public IActionResult ObtenerInmueblesPorTipo(int id)
        {
            var inmuebles = repoI.ObtenerInmueblesPorTipo(id);
            return Json(inmuebles);
        }

        [HttpGet]
        public IActionResult ListarInmuebles(int id, int limite = 5, int paginado = 1, int cantidad = 0)
        {
            ViewBag.limite = limite;

            ViewBag.rol = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

            // Obtener la cantidad total de filas de Propietario
            if (cantidad == 0)
            {
                cantidad = repoI.ObtenerCantidadDeFilas();
            }

            // Calcula el número total de páginas
            ViewBag.totalPages = (int)Math.Ceiling((double)cantidad / limite);
            ViewBag.idPropietario = id;
            // Establece la página actual en `ViewBag`
            ViewBag.currentPage = paginado;
            return View(repoI.ObtenerInmueblesPorPropietario(id, limite, paginado));
        }

        [HttpGet]
        public IActionResult PaginadoListarInmuebles(int paginado, int limite)
        {
            // Asegúrate de recibir el valor de `limite` y `paginado`
            ViewBag.limite = limite;
            return Json(repoI.ObtenerInmuebles(limite, paginado));
        }

        [HttpGet]
        public ActionResult BuscarInquilino(int dni)
        {
            var inquilino = repoIn.ObtenerInquilinoPorDNI(dni);
            if (inquilino != null)
            {
                // Si el inquilino se encuentra, devolvemos los datos como un objeto JSON con la propiedad "success" igual a true
                // y los datos del inquilino en la propiedad "inquilino"

                return Json(new { success = true, inquilino = inquilino });
            }
            else
            {
                // Si el inquilino no se encuentra, devolvemos un objeto JSON con la propiedad "success" igual a false
                return Json(new { success = false });
            }
        }

        public IActionResult NoAutorizado()
        {
            return View(); // Puedes redirigir a una vista específica para mostrar un mensaje de error o realizar alguna acción.
        }

        // Filtro de acción para redirigir si el usuario no está autenticado
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (!User.Identity.IsAuthenticated)
            {

Views/Inmueble/Alta.cshtml
@model inmobiliariaBaigorriaDiaz.Models.Inmueble

@{
	ViewData["Title"] = "Alta";
}

<div class="container mt-3">
	<div class="row justify-content-center">
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<h1 class="text-center"><b>ALTA DEL INMUEBLE</b></h1>
					<h2 class="text-center">¿Está seguro que desea dar de alta de nuevo al siguiente inmueble?</h2>
					<hr />
					<dl class="row">
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.IdInmueble)
						</dt>
						<dd class="col-sm-8">
							@Html.DisplayFor(model => model.IdInmueble)
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Direccion)
						</dt>
						<dd class="col-sm-8">
							@Html.DisplayFor(model => model.Direccion)
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Tipo.Nombre)
						</dt>
						<dd class="col-sm-8">
							@Html.DisplayFor(model => model.Tipo.Nombre)
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Ambientes)
						</dt>
						<dd class="col-sm-8">
							@Html.DisplayFor(model => model.Ambientes)
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Superficie)
						</dt>
						<dd class="col-sm-8">
							@Html.DisplayFor(model => model.Superficie)
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Longitud)
						</dt>
						<dd class="col-sm-8">
							@Html.DisplayFor(model => model.Longitud)
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Latitud)
						</dt>
						<dd class="col-sm-8">
							@Html.DisplayFor(model => model.Latitud)
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Precio)
						</dt>
						<dd class="col-sm-8">
							@Html.DisplayFor(model => model.Precio)
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Uso.Nombre)
						</dt>
						<dd class="col-sm-8">
							@Html.DisplayFor(model => model.Uso.Nombre)
						</dd>
						<dt class="col-sm-4">
							@Html.DisplayNameFor(model => model.Estado)
						</dt>
						<dd class="col-sm-8">
							@if (!Model.Estado)
							{
								<span>No Disponible</span>
							}
							else
							{
								<span>Disponible</span>
							}
						</dd>
						<dt class="col-sm-4">
							<span>Dueño</span>
						</dt>
						<dd class="col-sm-8">
							@(Model.Duenio?.ToString())
						</dd>
						<dd class="col-sm-12"></dd>
					</dl>
					<div class="text-center">
						<form asp-action="Alta">
							<input type="submit" value="Alta" class="btn btn-success" style="margin-right: 30px;" />
							<button type="button" onclick="window.location.href='@Url.Action("Index", "Inmueble")'"
								class="btn btn-outline-warning" style="font-weight: bold; border-width: 2px;"> Volver a
								la Lista</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Views/Inmueble/Create.cshtml
@model inmobiliariaBaigorriaDiaz.Models.Inmueble

@{
    ViewData["Title"] = "Create";
}

<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center"><b>ALTA DE INMUEBLE</b></h1>
                    <form asp-action="Create" class="needs-validation" novalidate id="formAltaInmueble">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label class="control-label">Propietario</label>
                            <input type="text" readonly class="form-control" value="@ViewBag.Duenio?.ToString()" />
                            <input type="hidden" asp-for="IdPropietario" value="@ViewBag.Duenio?.IdPropietario" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Direccion" class="control-label"></label>
                            <input asp-for="Direccion" class="form-control" />
                            <span asp-validation-for="Direccion" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Ambientes" class="control-label"></label>
                            <input asp-for="Ambientes" class="form-control" />
                            <span asp-validation-for="Ambientes" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Superficie" class="control-label"></label>
                            <input asp-for="Superficie" class="form-control" />
                            <span asp-validation-for="Superficie" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Longitud" class="control-label"></label>
                            <input asp-for="Longitud" class="form-control" />
                            <span asp-validation-for="Longitud" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Latitud" class="control-label"></label>
                            <input asp-for="Latitud" class="form-control" />
                            <span asp-validation-for="Latitud" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Precio" class="control-label"></label>
                            <input asp-for="Precio" class="form-control" />
                            <span asp-validation-for="Precio" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Uso del inmueble</label>
                            <select class="form-select" name="IdUsoDeInmueble">
                                <option disabled="" selected="" hidden="" value="">Seleccione un uso de inmueble
                                </option>
                                @foreach (var item in ViewBag.UsosDeInmuebles)
                                {
                                    <option value="@item.IdUsoDeInmueble">@(item.Nombre)</option>
                                }
                            </select>
                            <span asp-validation-for="IdUsoDeInmueble" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="IdTipoDeInmueble" class="control-label">Tipo de inmueble</label>
                            <div class="select-group">
                                <select asp-for="IdTipoDeInmueble" class="form-select" name="IdTipoDeInmueble">
                                    <option disabled="" selected="" hidden="" value="">Seleccione un tipo de inmueble
                                    </option>
                                    @foreach (var item in ViewBag.TiposDeInmuebles)
                                    {
                                        <option value="@item.IdTipoDeInmueble">@(item.Nombre)</option>
                                    }
                                    <span class="option-group">
                                        <i class="fa fa-check text-success d-none"></i>
                                        <i class="fa fa-times text-danger d-none"></i>
                                    </span>
                                    <div class="invalid-feedback">Seleccione un tipo de inmueble</div>
                                </select>
                            </div>
                            <span asp-validation-for="IdTipoDeInmueble" class="text-danger"></span>
                            <input type="hidden" id="idPropietario" name="idPropietario" value="" />
                            <div class="form-group text-center mt-2">
                                <button type="submit" class="btn btn-primary">Alta</button>
                                <a href="@Url.Action("Index", "Inmueble")"
                                    class="m-2 p-2 btn btn-outline-warning">Volver a
                                    la Lista</a>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.input-group input').on('input', function () {
                var inputGroup = $(this).closest('.input-group');
                var iconCheck = inputGroup.find('.fa-check');
                var iconTimes = inputGroup.find('.fa-times');
                if ($(this).val().trim() !== '') {
                    iconCheck.removeClass('d-none');
                    iconTimes.addClass('d-none');
                } else {
                    iconCheck.addClass('d-none');
                    iconTimes.removeClass('d-none');
                }
            });
        });
    </script>
}

Views/Inmueble/Delete.cshtml
@model inmobiliariaBaigorriaDiaz.Models.Inmueble

@{
    ViewData["Title"] = "Eliminar";
}

<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center"><b>BAJA DEL INMUEBLE</b></h1>
                    <h2 class="text-center">¿Está seguro que desea dar de baja al siguiente inmueble?</h2>
                    <hr />
                    <dl class="row">
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.IdInmueble)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.IdInmueble)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Direccion)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Direccion)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Tipo.Nombre)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Tipo.Nombre)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Ambientes)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Ambientes)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Superficie)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Superficie)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Longitud)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Longitud)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Latitud)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Latitud)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Precio)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Precio)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Uso.Nombre)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Uso.Nombre)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Estado)
                        </dt>
                        <dd class="col-sm-8">
                            @if (!Model.Estado)
                            {
                                <span>No Disponible</span>
                            }
                            else
                            {
                                <span>Disponible</span>
                            }
                        </dd>
                        <dt class="col-sm-4">
                            <span>Dueño</span>
                        </dt>
                        <dd class="col-sm-8">
                            @(Model.Duenio?.ToString())
                        </dd>
                        <dd class="col-sm-12"></dd>
                    </dl>
                    <div class="text-center">
                        <form asp-action="Delete">
                            <input type="submit" value="Baja" class="btn btn-danger" style="margin-right: 30px;" />
                            <button type="button" onclick="window.location.href='@Url.Action("Index", "Inmueble")'"
                                class="btn btn-outline-warning" style="font-weight: bold; border-width: 2px;"> Volver a la Lista</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Inmueble/Details.cshtml
@model inmobiliariaBaigorriaDiaz.Models.Inmueble

@{
    ViewData["Title"] = "Detalles";
}

<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center"><b>DETALLE DEL INMUEBLE</b></h1>
                    <hr />
                    <dl class="row">
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.IdInmueble)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.IdInmueble)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Direccion)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Direccion)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Tipo.Nombre)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Tipo.Nombre)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Ambientes)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Ambientes)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Superficie)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Superficie)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Longitud)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Longitud)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Latitud)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Latitud)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Precio)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Precio)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Uso.Nombre)
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Uso.Nombre)
                        </dd>
                        <dt class="col-sm-4">
                            @Html.DisplayNameFor(model => model.Estado)
                        </dt>
                        <dd class="col-sm-8">
                            @if (!Model.Estado)
                            {
                                <span>No Disponible</span>
                            }
                            else
                            {
                                <span>Disponible</span>
                            }
                        </dd>
                        <dt class="col-sm-4">
                            <span>Dueño</span>
                        </dt>
                        <dd class="col-sm-8">
                            @(Model.Duenio?.ToString())
                        </dd>
                        <dd class="col-sm-12"></dd>
                    </dl>
                    <div class="text-center">
                        <a href="@Url.Action("Edit", new { id = Model.IdInmueble })" class="btn btn-primary btn-editar"
                            style="margin-right: 30px;">Editar</a>
                        <button type="button" onclick="window.location.href='@Url.Action("Index", "Inmueble")'"
                            class="btn btn-outline-warning" style="font-weight: bold; border-width: 2px;"> Volver a la
                            Lista</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>